
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace ModelDeteksiHoaks.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelDeteksiHoaks.ModelInput sampleData = new ModelDeteksiHoaks.ModelInput()
            {
                V2 = @"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...",
                Col2 = @"Congratulations! You have won a 1 week FREE membership in our $100,000 Prize Jackpot! To claim your prize call now 09061701461. Claim code KL341. Valid 12 hours only.",
                Col3 = @"",
                Col4 = @"",
            };


            Console.WriteLine("Using model to make single prediction -- Comparing actual V1 with predicted V1 from sample data...\n\n");


            Console.WriteLine($"V1: {@"ham"}");
            Console.WriteLine($"V2: {@"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."}");
            Console.WriteLine($"Col2: {@""}");
            Console.WriteLine($"Col3: {@""}");
            Console.WriteLine($"Col4: {@""}");


            var sortedScoresWithLabel = ModelDeteksiHoaks.PredictAllLabels(sampleData);
            Console.WriteLine($"{"Class",-40}{"Score",-20}");
            Console.WriteLine($"{"-----",-40}{"-----",-20}");

            foreach (var score in sortedScoresWithLabel)
            {
                Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
            }
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
